name = "Dynare"
uuid = "5203de40-99df-439e-afbc-014de65cb9ef"
authors = ["michel "]
version = "0.7.5"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
AdvancedMH = "5b7e9947-ddc0-4b3f-9b55-0d8042f74170"
AxisArrayTables = "af8da316-43a4-49f0-bd76-7de0cd630fd6"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
DynarePreprocessor_jll = "23afba7c-24e5-5ee2-bc2c-b42e07f0492a"
ExtendedDates = "78f5a1cc-aa73-4dda-b6b2-4d6b1976988f"
FastLapackInterface = "29a986be-02c6-4525-aec4-84b980013641"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KOrderPerturbations = "469b1a10-d817-41b3-9228-c19fbf63afb5"
KalmanFilterTools = "ec016732-9331-11e9-305f-d53cb440b85a"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
LinearRationalExpectations = "45f42fbc-210c-4ecc-9452-59ec793b9bfd"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolynomialMatrixEquations = "4f9d485d-518f-41ed-81c8-372cd804c93b"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
TransformedLogDensities = "f9bc47f6-f3f8-4f3b-ab21-f8bc73906f26"

[weakdeps]
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"

[extensions]
PardisoSolver = ["MKL", "Pardiso"]
PathSolver = "PATHSolver"

[compat]
AbstractMCMC = "4.4.0"
AdvancedMH = "0.7.4"
AxisArrayTables = "0.1.2"
BenchmarkTools = "1.2.2"
CSV = "0.10.2"
DataFrames = "1.3.2"
Distances = "0.10.7"
Distributions = "0.25.66"
DynamicHMC = "3.1.2"
DynarePreprocessor_jll = "~6.3.0"
ExtendedDates = "0.2.0"
FastLapackInterface = "2.0.0"
FiniteDiff = "2.13.1"
Formatting = "0.4.2"
IntervalSets = "0.6.2, 0.7"
IterativeSolvers = "0.9.2"
JLD2 = "0.4.22"
JSON = "0.21.2"
KalmanFilterTools = "0.1.3"
KernelDensity = "0.6.5"
KOrderPerturbations = "0.1.1"
LineSearches = "7.1.1"
LinearMaps = "3.5.1"
LinearRationalExpectations = "0.5"
LogDensityProblems = "0.11.5, 2"
MCMCChains = "5.3.1, 6"
MCMCDiagnosticTools = "0.3"
MKL = "0.6"
NLSolversBase = "7.8.2"
Optim = "1.7.3"
PATHSolver = "1"
Pardiso = "0.5"
Plots = "1.25.7"
PolynomialMatrixEquations = "0.2.0"
PrettyTables = "1.3.1, 2"
ProximalOperators = "0.15.3"
Reexport = "1.2.2"
Requires = "1.3.0"
Roots = "2.0.8"
RuntimeGeneratedFunctions = "0.5.3"
SpecialFunctions = "2.1.7"
StatsFuns = "0.9.15, 1"
StatsPlots = "0.15"
Suppressor = "0.2.0"
Tokenize = "=0.5.21"
TransformVariables = "0.6.2, 0.7, 0.8"
TransformedLogDensities = "1.0"
julia = "1.6.3"
